alias aliases='cat ~/.bash_aliases; echo "───── local ────";cat ~/.local.bash_aliases'
alias b='byobu'
alias buffer='subl $BYOBU_RUN_DIR/printscreen'
alias dg='bloop projects --dot-graph | dot -Tpdf -o dependency-graph.pdf && xdg-open dependency-graph.pdf'
alias gi='git init && git add . && git commit -am "Initial commit"'
alias ipp='curl https://ipecho.net/plain; echo'
alias new-install-repo='sbtnoss new git@github.com:agilesteel/install-seed.g8.git'
alias sbtnoss='sbt --supershell=false'
